### ISSUE TITLE
Giving error 'Sorry an error occured, please try again later' after using !statusrefresh

### ISSUE THREAD

**Issue by Circir1337** [discord-gamestatus/discord-gamestatus#47]
Hi, i updated statusmod image then tried to refresh, then i got this error.. Any idea? (The bot perm and channel perm have 'can send embed files' permission.)
![image](https://user-images.githubusercontent.com/37486634/184982736-5acad3ee-bcf1-4b5e-8fba-c47db8450625.png)

**Comment by Douile** [comment]
Could you show us what statusmod reports your settings as

**Comment by Circir1337** [comment]
Solved.
